[package]
name = "pushover_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.4" }
reqwest = { version = "0.11", features = ["serde_json", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "rt"] }
toml = "0.8"
